name: Renovate

on:
  schedule:
    - cron: '0 3 * * *'  # 毎日午前3時に実行
  workflow_dispatch:  # 手動実行も可能

jobs:
  renovate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Self-hosted Renovate
        uses: renovatebot/github-action@v40.3.1
        with:
          configurationFile: renovate.json
          token: ${{ secrets.RENOVATE_TOKEN }}
        env:
          LOG_LEVEL: info