name: Scheduled Vulnerability Scan

on:
  workflow_dispatch:
  schedule:
    # 毎週金曜日の午前8時(UTC)に実行 (日本時間の午後5時)
    - cron: '0 8 * * 5'

jobs:
  scan-and-notify:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: read # ghcr.ioからイメージをpullするために必要

    steps:
      - name: Scan latest image with Trivy
        uses: aquasecurity/trivy-action@0.22.0
        with:
          image-ref: 'ghcr.io/${{ github.repository_owner }}/cli-tool-docker:latest'
          format: 'table'
          output: 'trivy-results.txt'
          exit-code: '0'
          ignore-unfixed: true
          vuln-type: 'os,library'
          severity: 'CRITICAL,HIGH'
          timeout: '30m'

      - name: Check scan results
        id: check_results
        run: |
          if [ -s "trivy-results.txt" ]; then
            echo "vulnerabilities_found=true" >> $GITHUB_OUTPUT
            # Slackのメッセージサイズ制限を考慮し、結果を一部抜粋または要約する
            echo "summary<<EOF" >> $GITHUB_OUTPUT
            head -n 50 trivy-results.txt >> $GITHUB_OUTPUT
            echo "EOF" >> $GITHUB_OUTPUT
          else
            echo "vulnerabilities_found=false" >> $GITHUB_OUTPUT
          fi

      - name: Notify Slack about vulnerabilities
        if: steps.check_results.outputs.vulnerabilities_found == 'true'
        uses: slackapi/slack-github-action@v1.26.0
        with:
          channel-id: 'C075AE23M9P' # 実際のチャンネルIDに置き換えてください
          payload: |
            {
              "text": "⚠️ 定期脆弱性スキャンで脆弱性が検出されました: ${{ github.repository }}",
              "blocks": [
                {
                  "type": "section",
                  "text": {
                    "type": "mrkdwn",
                    "text": "⚠️ *定期脆弱性スキャンレポート*\n`latest`イメージで脆弱性が検出されました。"
                  }
                },
                {
                  "type": "section",
                  "text": {
                    "type": "mrkdwn",
                    "text": "```${{ steps.check_results.outputs.summary }}```"
                  }
                },
                {
                  "type": "actions",
                  "elements": [
                    {
                      "type": "button",
                      "text": { "type": "plain_text", "text": "ワークフロー実行結果を見る" },
                      "url": "${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}"
                    }
                  ]
                }
              ]
            }
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}

      - name: Notify Slack about no vulnerabilities
        if: steps.check_results.outputs.vulnerabilities_found == 'false'
        uses: slackapi/slack-github-action@v1.26.0
        with:
          channel-id: 'C075AE23M9P' # 実際のチャンネルIDに置き換えてください
          payload: |
            {
              "text": "✅ 定期脆弱性スキャン完了: ${{ github.repository }}",
              "blocks": [
                {
                  "type": "section",
                  "text": {
                    "type": "mrkdwn",
                    "text": "✅ *定期脆弱性スキャン完了*\n`latest`イメージで新たな脆弱性は検出されませんでした。"
                  }
                }
              ]
            }
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
